### ISSUE TITLE
Upravit aktivitu připojování k serveru

### ISSUE THREAD

**Issue by malinajan** [xmarik1/train_manager#10]
Několik bodů k diskuzi (jsou to víceméně jen mé názory):

- Když probíhá připojování, skutečně zobrazit, že se něco děje, například točením nějakého točítka (jak že se to jmenuje v Androidu?)
- Podle mě stačí pro připojení k serveru zobrazit jednoduché vyskakovací okno s točítkem (např. [takovéto](http://img.wonderhowto.com/img/05/68/63575584553324/0/6-useful-android-gestures-you-might-not-know-about-already.w1456.jpg), jen s točítkem). Při připojování by tam bylo jen tlačítko "Zrušit" a text by do okna nepřibýval, ale postupně se měnit. Např. "Připojuji se k serveru..." -> "Autorizuji". Po úspěšném připojení by se hned přeslo do aktivity výběru oblastí řízení, po neúspěšném připojení by se zobrazilo ve vyskakovacím okně (jiném nebo stejném?) důvod neúspěšného připojení, tlačítko "Opakovat" a pokud by bylo důvodem neúspěšného připojení chyba v autorizaci, zobrazilo bys e i tlačítko pro změnu loginu.

Výše zmíněná funkcionalita samořejmě může zůstat i v existujícím okně, tlačítka "Změnit iniciály" a "Autorizuji" mi tam přijdou ale opravdu zbytečná.

**Comment by malinajan** [comment]
To, že se při klikání na tlačítko "zpět" dostanu do aktivity, která zobrazuje log připojování k serveru, mi přijd jako chyba.

**Comment by xmarik1** [comment]
už by se tam nemělo dát dostat tlačítkem zpět a je tam přidaný točítku

**Comment by malinajan** [comment]
Navrhuji ještě odtranit tlačíka "Autorizuji" a "Změnit iniciály". Když připojování selže na chybném heslu, klidně rovnou otevřít dialog pro změnu loginu.
