### ISSUE TITLE
Aktivita výběru oblastí řízení: opravdu zahrnou i seznam souprav?

### ISSUE THREAD

**Issue by malinajan** [xmarik1/train_manager#14]
Přemýšlel jsem nad aktivitou pro výběr oblastí řízení a přijde mi, že tato akvita kombinuje dvě úplně nesouvisející věci:

- žádost o novou soupravu do obastí řízení
- uvolňování souprav

Osobně navrhuji oddělit tyto 2 věci do speciálních aktivit. Připadá mi také intuitivnější, že když chci uvolnit loko z regulátoru, tak nevidím seznam oblastí řízení. A naopak, když chci žádat o novou lokomotivu, nezajímá mě senzam aktuálních lokomotiv.

Teď mi v aktivitě také nesedí, že je nezjdřív seznam oblastí řízení, pak seznam lokmotiv, a pak tlačítko vztahující se k seznamu oblastí řízení.

Opravdu ych to udělal víc intuitivní.

Příklad:
Aktivita výběry oblastí rízení má název "Vyběrte OŘ", hned pod tím je text "Vyběrte oblast řízení, ve které chcete řídit vlak." Následuje seznam, pak text "Volitelná poznámka:", pod tím **velká** textArea pro poznámku a až pod tím tlačítko "Odeslat žádost"

**Comment by xmarik1** [comment]
dal sem to k sobě, jelikož se oboje stará o management zařízení, seznam loko se může hodit když se třeba zakecám a zapomenu jestli určitou lokio už mám nebo ne

**Comment by malinajan** [comment]
Pak bych se zamyslel nad tím, jak tlačítko se žádostí do oblasti řízení přiřadit výběru oblastí řízení, a nikoliv aby bylo až pod lokomotivami.

**Comment by malinajan** [comment]
Btw. Není pro tebe obecně jednodušší to rozdělit, abys nemusel v jedné aktivitě spravovat dvě celkem nezávislé věci? Chápu smysl seznamu lokomotiv, a chápu, že obojí souvisí s managementem zařízení, ale pořád mi přijde, že to spolu nesouvisí až tolik, aby to bylo ve stejné aktivitě, a že rozdělení ti usnadní spoustu práce. Například, když se změní orientace mobilu na landscape, seznam lokomotiv u mě úplně zmizí.

**Comment by xmarik1** [comment]
rozdělení, nebo změna umístění tlačítka + oprava otočení je, co se týče práce, zhruba na stejno

**Comment by malinajan** [comment]
Já osobně jsem pro rozdělení do samostatných aktivit. Ale akceptuji, že aplikace je tvé dílo a že můžeš mít jiný názor než já. Mám se třeba zkusit zeptat někoho dalšího? Nebo takto: Máš nějaký zásadní důvod pro ponechání obou věcí v jedné aktivitě, když je to obojí přibližně stejně náročné?

Mně přijde hezké, že když to rozdělíš do dvou aktivit, tak například úplně zmizí nutnost v aktivitě mít nadpisy "Oblasti řízení" a "Lokomotivy" (či jak je to teď), protože napis můžeš umístit přímo do modrého záhlaví (jak se to jmenuje?)

**Comment by xmarik1** [comment]
ok, sice se mě to popravdě nelíbí, ale si tady vlastně v roli zákazníka, takže to předělám na dvě, modrý záhlaví se tuším jmenuje header a definuje se v nějakém xml (v manifestu nebo tak někde)
