### ISSUE TITLE
Aktivita řízení loko: zobrazit více informací o loko v poli, kde se momentálně zobrazuje pouze její název

### ISSUE THREAD

**Issue by malinajan** [xmarik1/train_manager#18]
Navrhuji:
`název (označení) : adresa`

**Comment by xmarik1** [comment]
a je to nutné? informace jsou již zobrazeny ve výběru loko

**Comment by malinajan** [comment]
Podle mě by to bylo vhodné kvůli dvěma důvodům:

1) Typicky před sebou budeš mít obrazovku pro řízení lokomotiv, během řízení moc nebudeš chodit do jiných aktivit, tak by mi přišlo vhodné to tam zobrazit.
2) Přijde mi, že teď je tam nevyužité bílé místo.

**Comment by xmarik1** [comment]
však se nemusí chodit do jiných aktivit je to kousek nad tím, cca 1cm

**Comment by malinajan** [comment]
Ok, uznávám argument.
Pořád si ale myslím, že je škoda to místo nevyužít, když ho můžeme naplnit relevantními informacemi.
Nebo ti přijde, že jsou to přebytečné informace?

**Comment by xmarik1** [comment]
tak něco by tam určitě šlo dát, ale zvolil bych něco jiného než je nahoře, ale nevím co, co třeba domovská stanice? i když to asi ne,. klidně tam můžu dát i to stejné jako nahoře, akorát se mi to moc nelíbí

**Comment by malinajan** [comment]
Nic jako domovská stanice bohužel neeviduji.
Pokud se nepletu, v tom menu nahoře nezobrazuješ označení, ne? To by byla věc navíc.

**Comment by xmarik1** [comment]
jo to je dobrej nápad
