### ISSUE TITLE
Ikonka aplikace je příliš tmavá

### ISSUE THREAD

**Issue by malinajan** [xmarik1/train_manager#22]
![screenshot_20161223-150613](https://cloud.githubusercontent.com/assets/12673442/21455570/93eae802-c921-11e6-9055-9d3a341bd02b.png)

**Comment by xmarik1** [comment]
co myslíš, jak by vypadalo kdyby ta silueta byla bílá?

**Comment by malinajan** [comment]
Nemuselo by to vypadat špatně :).
Ještě mě napadlo nechat popředí šedou barvou, ale pozadí změnit na barvu horního navbaru v aplikaci (modrá), bylo by to konzistentní s barvou aplikace.

**Comment by xmarik1** [comment]
mám pocit, že už jsme to vyřešili, je to tak?

**Comment by malinajan** [comment]
Jo.
