### ISSUE TITLE
Aplikace na konec každé zprávy přidává prázdný řádek

### ISSUE THREAD

**Issue by malinajan** [xmarik1/train_manager#30]
@xmarik1 
Každá zpráva, kterou aplikace odesílá, končí znaky `\n\n`, je v ní tedy prázdný řádek navíc. To by aplikace neměla dělat. Navrhuji odstranit explicitní `\n` ze všech příkazů, které aplikace posílá, a spoléhat se na metodu TCP klienta `println`, která přidává symbol konce řádku za každou zprávu automaticky.

**Comment by xmarik1** [comment]
když sem tam to \n nepřidal, tak server padal a nedokázal zprávu zpracovat

**Comment by malinajan** [comment]
Já jsem to `\n` zkoušel odstranit a normálně to fungovalo... Zkusím to pořádně a kdyžtak udělám pull request.

**Comment by malinajan** [comment]
Odebral jsem `\n` a server zpravy normalne zpracovava. Mas pull request.
