### ISSUE TITLE
Doladit názvy aktivit v záhlaví

### ISSUE THREAD

**Issue by malinajan** [xmarik1/train_manager#7]
Zobrazovat v záhlaví rozumné názvy. V Českém prostředí české, pokud chceš přidat podoporu jiných prostředí, klidně, pro mě je nejdůležitejší to české.

**Comment by xmarik1** [comment]
pokud si nemyslel název train_manager tak by to melo byt ok

**Comment by malinajan** [comment]
Myslel jsem ten i všechny ostatní. Nechceš upravit třeba na *Train Manager*?
