### ISSUE TITLE
Aktivita výběru serveru: neumožnit přejít do aktivit, které vyžadují připojení

### ISSUE THREAD

**Issue by malinajan** [xmarik1/train_manager#9]
Neumožnit přejít do *Rozhraní vlaku* a *Výběr vlaku*, protože tyto aktivity jsou podmíněné existujícím připojením k serveru a úspěšnou autorizací.
Pokud chceš zachovat hamburger, navrhuji v něm zašedit výše zmíněné položky.

**Comment by xmarik1** [comment]
sme se bavili, že bych to tam nechal, aby si to mohl člověk projít i doma, když by neměl připojení k serveru

**Comment by malinajan** [comment]
Pamatuji si na to, možná bych to ale ještě zvážil. Mně osobně přijde, že když k té aplikaci poprvé přijdeš, tak to, že si to můžeš proklikat ti moc nedá, spíš to klade nároky na vývojáře, aby například nepadlo řízení, které neobsahuje žádnou lokomotivu. Přijde mi, že třeba v rozhraní pro řízení vlaku vypadá stejně alespoň polovina položek jinak, protože prostě nejsou naplněny obsahem. Také mi přijde, že v těch apliakcích, které jsme zkoušeli ve čtvrtek, taková možnost taky nebyla a nechyběla mi.

Myslíš, že je užitečné nechat uživatele proklikat si aplikaci? Jaký vidíš účel?

**Comment by xmarik1** [comment]
člověk se může podívat třeba jak vypadá rozhraní pro řízení bez toho aby byl aktuálně u serveru, osobně znám pár lidí co appky hned mažou pokud se nemůžou nikam dostat aby se podívali jak to vypadá

**Comment by malinajan** [comment]
Mně to připadá tak trochu jako "nainstaloval jsem si na mobil SSH klienta, ale když neuvidím terminál bez připojení k serveru, tak aplikaci odinstaluji..."
Ale je to na tobě, když myslíš, že je to užitečné...

**Comment by xmarik1** [comment]
osobně znám dost lidí co si chcou aplikaci aspoň proklikat, nebo podívat jak to vypadá, ale ok, je zamčené
